kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: toolchain-enabler
rules:
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  verbs:
  - '*'
- apiGroups:
  - ""
  - project.openshift.io
  resources:
  - projectrequests
  verbs:
  - create
- apiGroups:
  - codeready.io
  resources:
  - toolchainenablers/finalizers
  verbs:
  - update
