apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: toolchainenablers.codeready.openshift.io
spec:
  group: codeready.openshift.io
  names:
    kind: ToolChainEnabler
    listKind: ToolChainEnablerList
    plural: toolchainenablers
    singular: toolchainenabler
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            authURL:
              type: string
            clusterName:
              type: string
            clusterURL:
              type: string
            toolChainSecretName:
              type: string
          required:
          - authURL
          - clusterURL
          - clusterName
          - toolChainSecretName
          type: object
        status:
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
