# Todo: We may remove this in future if needed at all
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: toolchainenablers.codeready.io
spec:
  group: codeready.io
  names:
    kind: ToolChainEnabler
    listKind: ToolChainEnablerList
    plural: toolchainenablers
    singular: toolchainenabler
  scope: Namespaced
  version: v1alpha1
