kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: toolchain-enabler
rules:
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - ""
  - project.openshift.io
  resources:
  - projectrequests
  verbs:
  - create
- apiGroups:
  - codeready.openshift.io
  resources:
  - toolchainenablers/finalizers
  verbs:
  - update
- apiGroups:
  - ""
  - oauth.openshift.io
  resources:
  - oauthclients
  - limitranges
  - resourcequotas
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  - authorization.openshift.io
  resources:
  - rolebindingrestrictions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  - build.openshift.io
  resources:
  - builds
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  - apps.openshift.io
  resources:
  - deploymentconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - config.openshift.io
  resources:
  - infrastructures
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - ""
  - user.openshift.io
  resources:
  - users
  - identities
  - useridentitymappings
  verbs:
  - get
  - list
  - create
  - update
  - delete
  - watch
- apiGroups:
  - ""
  - quota.openshift.io
  resources:
  - clusterresourcequotas
  verbs:
  - get
  - list
  - create
  - update
  - delete
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - patch
  - delete
  - watch
- apiGroups:
  - ""
  - oauth.openshift.io
  resources:
  - oauthaccesstokens
  - oauthclientauthorizations
  verbs:
  - get
  - list
  - delete
  - deletecollection
  - watch
- apiGroups:
  - ""
  - user.openshift.io
  resources:
  - users
  - groups
  verbs:
  - impersonate
