apiVersion: v1
kind: ServiceAccount
metadata:
  name: toolchain-enabler
  namespace: REPLACE_NAMESPACE

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: toolchain-enabler
  namespace: REPLACE_NAMESPACE
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - events
  - configmaps
  - secrets
  - serviceaccounts
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - route.openshift.io
  resources:
  - routes
  verbs:
  - create
  - delete
- apiGroups:
  - codeready.openshift.io
  resources:
  - toolchainenablers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: toolchain-enabler
  namespace: REPLACE_NAMESPACE
subjects:
- kind: ServiceAccount
  name: toolchain-enabler
roleRef:
  kind: Role
  name: toolchain-enabler
  apiGroup: rbac.authorization.k8s.io
