apiVersion: apps/v1
kind: Deployment
metadata:
  name: toolchain-enabler
spec:
  replicas: 1
  selector:
    matchLabels:
      name: toolchain-enabler
  template:
    metadata:
      labels:
        name: toolchain-enabler
    spec:
      serviceAccountName: toolchain-enabler
      containers:
        - name: toolchain-enabler
          # replace it when running operator with latest built container image.
          image: REPLACE_IMAGE
          ports:
          - containerPort: 60000
            name: metrics
          imagePullPolicy: IfNotPresent
          readinessProbe:
            exec:
              command:
                - stat
                - /tmp/operator-sdk-ready
            initialDelaySeconds: 4
            periodSeconds: 10
            failureThreshold: 1
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: AUTH_URL
              valueFrom:
                configMapKeyRef:
                  name: toolchain
                  key: auth.url
            - name: CLUSTER_URL
              valueFrom:
                configMapKeyRef:
                  name: toolchain
                  key: cluster.url
            - name: CLUSTER_NAME
              valueFrom:
                configMapKeyRef:
                  name: toolchain
                  key: cluster.name
            - name: TC_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: toolchain
                  key: tc.client.id
            - name: TC_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: toolchain
                  key: tc.client.secret
