apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: toolchain-enabler
  namespace: codeready-toolchain
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - events
  - configmaps
  - secrets
  - serviceaccounts
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - route.openshift.io
  resources:
  - routes
  verbs:
  - create
  - delete
- apiGroups:
  - codeready.openshift.io
  resources:
  - toolchainenablers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
